# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jSjKx14br4BXualZi3bAbNUgnwbitQsU
"""

import pandas as pd 
df = pd.read_csv('/content/spam_ham_dataset.csv') 
from nltk.tokenize import RegexpTokenizer
def clean_str(string, reg = RegexpTokenizer(r'[a-z]+')): 
    # Clean a string with RegexpTokenizer
    string = string.lower() 
    tokens = reg.tokenize(string) 
    return " ".join(tokens) 
df['text_clean'] = df['text'].apply(lambda string: clean_str(string))
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(df.text_clean)
y = df.label
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X,y) 
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(X,y)
def predict(mail):
  #convert text to feature vectors
  mail_features = cv.transform(mail) 
  prediction = model.predict(mail_features) 
  if(prediction[0]=='spam'):
    print('Spam mail')
  else:
    print('Ham mail')
import joblib 
joblib.dump(model,'pickle.pkl') 
joblib.dump(X,'transform.pkl')